In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [4]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [5]:
df = pd.DataFrame({
    "soli_moisture": [0.10, 0.15, 0.20, 0.40, 0.60, 0.35, 0.18, 0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22, 35, 24, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 10, 3, 10, 12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1]
})

In [6]:
df

    soli_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.40             22               4            0
4            0.60             28              10            0
5            0.35             30               3            0
6            0.18             19              10            1
7            0.45             22              12            0
8            0.05             35               5            1
9            0.80             24               9            0
10           0.27             33              11            1
11           0.55             21               2            0
12           0.70             25               6            0
13           0.12             20               1            1
14           0.30             29               9            1

In [7]:
df.columns

Index(['soli_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [8]:
X = df[['soli_moisture', 'temperature_c', 'sunlight_hours', 'needs_water']]
y = df['needs_water']

In [9]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [10]:
X_scaled

    soli_moisture  temperature_c  sunlight_hours  needs_water
0        0.066667         0.9375        0.727273          1.0
1        0.133333         0.6875        0.636364          1.0
2        0.200000         0.4375        0.545455          1.0
3        0.466667         0.1875        0.272727          0.0
4        0.733333         0.5625        0.818182          0.0
5        0.400000         0.6875        0.181818          0.0
6        0.173333         0.0000        0.818182          1.0
7        0.533333         0.1875        1.000000          0.0
8        0.000000         1.0000        0.363636          1.0
9        1.000000         0.3125        0.727273          0.0
10       0.293333         0.8750        0.909091          1.0
11       0.666667         0.1250        0.090909          0.0
12       0.866667         0.3750        0.454545          0.0
13       0.093333         0.0625        0.000000          1.0
14       0.333333         0.6250        0.727273          1.0

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42, stratify=y)

In [ ]:
# Make the ANN( Artificial Neural Network )

In [12]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8, activation = 'relu'),
    layers.Dense(1, activation = 'sigmoid')
])

In [13]:
model.compile(optimizer='sgd', loss = 'binary_crossentropy', metrics=['accuracy'])

In [14]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 114ms/step - accuracy: 0.3636 - loss: 0.7843 - val_accuracy: 0.5000 - val_loss: 0.7443
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3636 - loss: 0.7732 - val_accuracy: 0.5000 - val_loss: 0.7344
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3636 - loss: 0.7621 - val_accuracy: 0.5000 - val_loss: 0.7260
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3636 - loss: 0.7523 - val_accuracy: 0.5000 - val_loss: 0.7181
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3636 - loss: 0.7442 - val_accuracy: 0.5000 - val_loss: 0.7099
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.3636 - loss: 0.7354 - val_accuracy: 0.7500 - val_loss: 0.7025
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3636 - loss: 0.7285 - val_accuracy: 0.7500 - val_loss: 0.6966
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.3636 - loss: 0.7214 - val_accuracy: 0.7500 - val_loss: 0.6888
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4545 - loss: 0.7132 - val_accuracy: 0.7500 - val_loss: 0.6833
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.7076 - val_accuracy: 0.7500 - val_loss: 0.6788
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.7004 - val_accuracy: 0.7500 - val_loss: 0.6745
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6364 - loss: 0.6942 - val_accuracy: 0.7500 - val_loss: 0.6704
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7273 - loss: 0.6882 - val_accuracy: 0.7500 - val_loss: 0.6665
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7273 - loss: 0.6836 - val_accuracy: 0.5000 - val_loss: 0.6628
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7273 - loss: 0.6774 - val_accuracy: 0.5000 - val_loss: 0.6587
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6711 - val_accuracy: 0.5000 - val_loss: 0.6563
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6659 - val_accuracy: 0.5000 - val_loss: 0.6541
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6613 - val_accuracy: 0.5000 - val_loss: 0.6519
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6575 - val_accuracy: 0.7500 - val_loss: 0.6488
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6524 - val_accuracy: 0.7500 - val_loss: 0.6470
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6487 - val_accuracy: 0.7500 - val_loss: 0.6450
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8182 - loss: 0.6449 - val_accuracy: 0.7500 - val_loss: 0.6430
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6421 - val_accuracy: 0.7500 - val_loss: 0.6408
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8182 - loss: 0.6395 - val_accuracy: 0.7500 - val_loss: 0.6387
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8182 - loss: 0.6364 - val_accuracy: 0.7500 - val_loss: 0.6370
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6336 - val_accuracy: 0.7500 - val_loss: 0.6349
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6303 - val_accuracy: 0.7500 - val_loss: 0.6329
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8182 - loss: 0.6278 - val_accuracy: 0.7500 - val_loss: 0.6307
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6251 - val_accuracy: 0.7500 - val_loss: 0.6288
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8182 - loss: 0.6225 - val_accuracy: 0.7500 - val_loss: 0.6264
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6197 - val_accuracy: 0.7500 - val_loss: 0.6245
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8182 - loss: 0.6176 - val_accuracy: 0.7500 - val_loss: 0.6221
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6143 - val_accuracy: 0.7500 - val_loss: 0.6202
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8182 - loss: 0.6118 - val_accuracy: 0.7500 - val_loss: 0.6184
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6099 - val_accuracy: 0.7500 - val_loss: 0.6159
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6068 - val_accuracy: 0.7500 - val_loss: 0.6139
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.6036 - val_accuracy: 0.7500 - val_loss: 0.6116
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.6009 - val_accuracy: 0.7500 - val_loss: 0.6098
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5987 - val_accuracy: 0.7500 - val_loss: 0.6077
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8182 - loss: 0.5961 - val_accuracy: 0.7500 - val_loss: 0.6059
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.5934 - val_accuracy: 0.7500 - val_loss: 0.6037
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8182 - loss: 0.5908 - val_accuracy: 0.7500 - val_loss: 0.6019
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7273 - loss: 0.5883 - val_accuracy: 0.7500 - val_loss: 0.6002
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7273 - loss: 0.5858 - val_accuracy: 0.7500 - val_loss: 0.5982
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7273 - loss: 0.5829 - val_accuracy: 0.7500 - val_loss: 0.5963
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7273 - loss: 0.5806 - val_accuracy: 0.7500 - val_loss: 0.5943
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7273 - loss: 0.5774 - val_accuracy: 0.7500 - val_loss: 0.5924
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7273 - loss: 0.5747 - val_accuracy: 0.7500 - val_loss: 0.5907
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5720 - val_accuracy: 0.7500 - val_loss: 0.5890
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.5693 - val_accuracy: 0.7500 - val_loss: 0.5873
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.5666 - val_accuracy: 0.7500 - val_loss: 0.5856
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8182 - loss: 0.5645 - val_accuracy: 0.7500 - val_loss: 0.5837
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5614 - val_accuracy: 0.7500 - val_loss: 0.5820
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8182 - loss: 0.5586 - val_accuracy: 0.7500 - val_loss: 0.5802
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.5564 - val_accuracy: 0.7500 - val_loss: 0.5783
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5536 - val_accuracy: 0.7500 - val_loss: 0.5765
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5510 - val_accuracy: 0.7500 - val_loss: 0.5748
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8182 - loss: 0.5482 - val_accuracy: 0.7500 - val_loss: 0.5732
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5460 - val_accuracy: 0.7500 - val_loss: 0.5713
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8182 - loss: 0.5427 - val_accuracy: 0.7500 - val_loss: 0.5696
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8182 - loss: 0.5414 - val_accuracy: 0.7500 - val_loss: 0.5678
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9091 - loss: 0.5377 - val_accuracy: 0.7500 - val_loss: 0.5661
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9091 - loss: 0.5350 - val_accuracy: 0.7500 - val_loss: 0.5645
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9091 - loss: 0.5330 - val_accuracy: 0.7500 - val_loss: 0.5627
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9091 - loss: 0.5297 - val_accuracy: 0.7500 - val_loss: 0.5611
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9091 - loss: 0.5273 - val_accuracy: 0.7500 - val_loss: 0.5595
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9091 - loss: 0.5262 - val_accuracy: 0.7500 - val_loss: 0.5580
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9091 - loss: 0.5225 - val_accuracy: 0.7500 - val_loss: 0.5565
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9091 - loss: 0.5196 - val_accuracy: 0.7500 - val_loss: 0.5549
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9091 - loss: 0.5174 - val_accuracy: 0.7500 - val_loss: 0.5533
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9091 - loss: 0.5155 - val_accuracy: 0.7500 - val_loss: 0.5517
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9091 - loss: 0.5122 - val_accuracy: 0.7500 - val_loss: 0.5500
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9091 - loss: 0.5100 - val_accuracy: 0.7500 - val_loss: 0.5481
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9091 - loss: 0.5073 - val_accuracy: 0.7500 - val_loss: 0.5463
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9091 - loss: 0.5044 - val_accuracy: 0.7500 - val_loss: 0.5446
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9091 - loss: 0.5021 - val_accuracy: 0.7500 - val_loss: 0.5428
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9091 - loss: 0.5000 - val_accuracy: 0.7500 - val_loss: 0.5408
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9091 - loss: 0.4970 - val_accuracy: 0.7500 - val_loss: 0.5390
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9091 - loss: 0.4958 - val_accuracy: 0.7500 - val_loss: 0.5372
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9091 - loss: 0.4925 - val_accuracy: 0.7500 - val_loss: 0.5355
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4901 - val_accuracy: 0.7500 - val_loss: 0.5336
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9091 - loss: 0.4880 - val_accuracy: 0.7500 - val_loss: 0.5318
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4852 - val_accuracy: 0.7500 - val_loss: 0.5301
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9091 - loss: 0.4829 - val_accuracy: 0.7500 - val_loss: 0.5284
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4808 - val_accuracy: 0.7500 - val_loss: 0.5265
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4780 - val_accuracy: 0.7500 - val_loss: 0.5248
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4756 - val_accuracy: 0.7500 - val_loss: 0.5232
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9091 - loss: 0.4737 - val_accuracy: 0.7500 - val_loss: 0.5216
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4709 - val_accuracy: 0.7500 - val_loss: 0.5199
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4689 - val_accuracy: 0.7500 - val_loss: 0.5181
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4662 - val_accuracy: 0.7500 - val_loss: 0.5166
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9091 - loss: 0.4643 - val_accuracy: 0.7500 - val_loss: 0.5147
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4612 - val_accuracy: 0.7500 - val_loss: 0.5124
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4589 - val_accuracy: 0.7500 - val_loss: 0.5101
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4574 - val_accuracy: 0.7500 - val_loss: 0.5078
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4541 - val_accuracy: 0.7500 - val_loss: 0.5056
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4527 - val_accuracy: 0.7500 - val_loss: 0.5031
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.4504 - val_accuracy: 0.7500 - val_loss: 0.5007
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.4472 - val_accuracy: 0.7500 - val_loss: 0.4984
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9091 - loss: 0.4446 - val_accuracy: 0.7500 - val_loss: 0.4961

In [15]:
from tensorflow.keras import optimizers

In [17]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)